spring:
  kafka:
    bootstrap-servers: localhost:9092

collector:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.telemetry.collector: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN