spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?sslmode=disable
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration

grpc:
  server:
    port: 59091
    reflection-service-enabled: true
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.engine.jdbc: DEBUG
    org.postgresql: DEBUG
    #    io.grpc: DEBUG
    #    net.devh.boot.grpc: DEBUG
    ru:
      yandex:
        practicum:
          telemetry:
            analyzer:
              DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"

kafka:
  bootstrap-servers: localhost:9092

  consumer:
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer